[tool.poetry]
name = "flastel"
version = "0.0.1"
description = "Flastel â€“ Telegram Bot API, create bot's"
authors = ["Dmitry Kolodnyanskyi dere96632@gmail.com"]

[tool.poetry.dependencies]
python = "^3.x"
aiohttp = "^3.x"
asyncio = "^3.x"
logging = "^1.x"
